services:
  app:
    image: cosmtrek/air:latest
    working_dir: /app
    command: sh -c "go mod download && air -c .air.toml"
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env
    environment:
      GOTOOLCHAIN: go1.25.3
    ports:
      - "8080:8080"
volumes:
  go-mod-cache:
    driver: local
